name: Andriod Build

on: pull_request

jobs: 
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Granting permission
        run: chmod +x gradlew
          
      - name: Run Tests
        run: ./gradlew testDebugUnitTest
        
      - name: Build Project
        run: ./gradlew assemble
